module Fayde.Controls {
    import IValueConverter = Data.IValueConverter;
    import PropertyPath = Data.PropertyPath;
    import BindingMode = Data.BindingMode;
    import Binding = Data.Binding;
    export class DataGridBindingInfo {

        private m_binding: Binding;
        private m_autoGenerated: boolean;

        constructor()
        constructor(path: string,readOnly: boolean,autoGenerated: boolean)
        constructor(path?: string,readOnly?: boolean,autoGenerated?: boolean){
            if(readOnly != null){
                this.ReadOnly  = readOnly;
                this.m_autoGenerated = autoGenerated;
            }
        }

        public get IsAutoGenerated():boolean{return this.m_autoGenerated;}

        public get BindsDirectlyToSource():boolean{return this.m_autoGenerated;}
        public set BindsDirectlyToSource(value: boolean){
            this.m_autoGenerated = false;
            this.m_binding.BindsDirectlyToSource = value;
        }

        public get Converter():IValueConverter{return this.m_binding.Converter;}
        public set Converter(value: IValueConverter){
            this.m_autoGenerated = false;
            this.m_binding.Converter = value;
        }

        public get ConverterCulture():any{return this.m_binding.ConverterCulture;}
        public set ConverterCulture(value: any){
            this.m_autoGenerated = false;
            this.m_binding.ConverterCulture = value;
        }

        public get ConverterParameter():any{return this.m_binding.ConverterParameter;}
        public set ConverterParameter(value: any){
            this.m_autoGenerated = false;
            this.m_binding.ConverterParameter = value;
        }

        public get ElementName():string{return this.m_binding.ElementName;}
        public set ElementName(value: string){
            this.m_autoGenerated = false;
            this.m_binding.ElementName = value;
        }

        public get FallbackValue():any{return this.m_binding.FallbackValue;}
        public set FallbackValue(value: any){
            this.m_autoGenerated = false;
            this.m_binding.FallbackValue = value;
        }

        public get Path():PropertyPath{return this.m_binding.FallbackValue;}
        public set Path(value: PropertyPath){
            this.m_autoGenerated = false;
            this.m_binding.FallbackValue = value;
        }

        public get ReadOnly():boolean{return this.m_binding.Mode == BindingMode.OneWay;}
        public set ReadOnly(value: boolean){
            this.m_autoGenerated = false;
            if(value){
                this.m_binding.Mode = BindingMode.OneWay;
            }else{
                this.m_binding.Mode = BindingMode.TwoWay;
            }
        }

        public get StringFormat():string{return this.m_binding.StringFormat;}
        public set StringFormat(value: string){
            this.m_autoGenerated = false;
            this.m_binding.StringFormat = value;
        }

        public get TargetNullValue():any{return this.m_binding.TargetNullValue;}
        public set TargetNullValue(value: any){
            this.m_autoGenerated = false;
            this.m_binding.TargetNullValue = value;
        }

        GetBinding(){
            return this.m_binding;
        }

    }
}